"""Shared naming, interface, and partition mechanics for source backends."""

from __future__ import annotations

import keyword
import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..ir import NormalizedGraph, NormalizedValue, ShapeDimension
from ..lowered import LoweredRegion
from ..schedule import AxisPartition, KernelStep, ScheduledRegion


class SourceEmissionError(ValueError):
    """Raised when a valid analytic schedule is outside the source backend."""


class SourceWriter:
    """Small deterministic indentation-aware source builder."""

    def __init__(self) -> None:
        self._lines: list[str] = []

    def line(self, indent: int = 0, text: str = "") -> None:
        """Append one line at ``indent`` levels."""

        self._lines.append(f"{'    ' * indent}{text}" if text else "")

    def render(self) -> str:
        """Return source with one canonical trailing newline."""

        return "\n".join(self._lines) + "\n"


@dataclass(frozen=True)
class Interface:
    """One-output PyPTO orchestration signature."""

    input_arguments: Mapping[str, str]
    output_value: str
    output_allocation_owner: str
    output_argument: str


@dataclass(frozen=True)
class EmissionContext:
    """Validated graph, problem, schedule, and ABI for one source backend."""

    graph: NormalizedGraph
    lowered: LoweredRegion
    schedule: ScheduledRegion
    step: KernelStep
    interface: Interface

    @property
    def region_id(self) -> str:
        return self.lowered.region_id


def interface(graph: NormalizedGraph, lowered: LoweredRegion) -> Interface:
    """Derive names for the currently supported one-output ABI."""

    if len(lowered.region_outputs) != 1:
        raise SourceEmissionError("source v1 supports exactly one region output")
    values = graph.value_map()
    input_arguments: dict[str, str] = {}
    used: set[str] = {"self", "pl", "region_index"}
    for index, value_id in enumerate(lowered.region_inputs):
        try:
            value = values[value_id]
        except KeyError as error:
            raise SourceEmissionError(
                f"region input {value_id!r} is absent from the normalized graph"
            ) from error
        if value.alias_of is not None:
            raise SourceEmissionError("source v1 does not emit aliased region inputs")
        name = unique_name(f"arg_{identifier(value.name or f'input_{index}')}", used)
        input_arguments[value_id] = name
    output_value = lowered.region_outputs[0]
    if output_value not in values:
        raise SourceEmissionError(
            f"region output {output_value!r} is absent from the normalized graph"
        )
    output_owner = lowered.output_allocation_owners[0]
    output_argument = unique_name("output", used)
    return Interface(input_arguments, output_value, output_owner, output_argument)


def program_header(
    program_name: str,
    io: Interface,
    graph: NormalizedGraph,
    work_units: int,
) -> SourceWriter:
    """Emit the common orchestration header for one homogeneous kernel."""

    values = graph.value_map()
    output = values[io.output_value]
    writer = SourceWriter()
    writer.line(0, '"""Generated by PTO-Fusebox from a solver-owned schedule."""')
    writer.line()
    writer.line(0, "import pypto.language as pl")
    writer.line()
    writer.line()
    writer.line(0, "@pl.program")
    writer.line(0, f"class {program_name}:")
    writer.line(1, "@pl.function(type=pl.FunctionType.Orchestration)")
    writer.line(1, "def main(")
    writer.line(2, "self,")
    for value_id, argument in io.input_arguments.items():
        writer.line(2, f"{argument}: {tensor_type(values[value_id])},")
    writer.line(2, f"{io.output_argument}: pl.Out[{tensor_type(output)}],")
    writer.line(1, f") -> {tensor_type(output)}:")
    writer.line(2, "with pl.manual_scope():")
    writer.line(3, f"for region_index in pl.parallel({work_units}):")
    return writer


def emit_partition_indices(
    writer: SourceWriter,
    indent: int,
    m_partition: AxisPartition,
    n_partition: AxisPartition,
    *,
    emit_extents: bool,
) -> None:
    """Emit deterministic coordinates for two solver-owned axis partitions."""

    writer.line(indent, f"m_index = region_index // {n_partition.parts}")
    writer.line(indent, f"n_index = region_index % {n_partition.parts}")
    _emit_axis_partition(writer, indent, "m", m_partition, emit_extent=emit_extents)
    _emit_axis_partition(writer, indent, "n", n_partition, emit_extent=emit_extents)


def _emit_axis_partition(
    writer: SourceWriter,
    indent: int,
    prefix: str,
    partition: AxisPartition,
    *,
    emit_extent: bool,
) -> None:
    if partition.big == partition.small:
        writer.line(
            indent,
            f"region_{'row' if prefix == 'm' else 'col'} = "
            f"{prefix}_index * {partition.big}",
        )
        if emit_extent:
            writer.line(
                indent,
                f"region_{'rows' if prefix == 'm' else 'cols'} = {partition.big}",
            )
        return
    writer.line(
        indent,
        f"{prefix}_big_before = pl.min({prefix}_index, {partition.num_big})",
    )
    writer.line(
        indent,
        f"region_{'row' if prefix == 'm' else 'col'} = "
        f"{prefix}_index * {partition.small} + {prefix}_big_before * "
        f"{partition.big - partition.small}",
    )
    if emit_extent:
        writer.line(
            indent,
            f"region_{'rows' if prefix == 'm' else 'cols'} = {partition.small} + "
            f"(pl.min({prefix}_index + 1, {partition.num_big}) - "
            f"{prefix}_big_before) * {partition.big - partition.small}",
        )


def validate_grid(
    step: KernelStep,
    work_units: int,
    m_partition: AxisPartition,
    n_partition: AxisPartition,
) -> None:
    """Check that launch and partition fields describe one grid."""

    if (
        step.parts_m != m_partition.parts
        or step.parts_n != n_partition.parts
        or work_units != m_partition.parts * n_partition.parts
    ):
        raise SourceEmissionError(
            "selected grid, partition, and work-unit counts disagree"
        )


def validate_partition_extent(
    partition: AxisPartition, extent: int, field: str
) -> None:
    """Check exact coverage of an axis partition."""

    covered = (
        partition.num_big * partition.big
        + (partition.parts - partition.num_big) * partition.small
    )
    if covered != extent:
        raise SourceEmissionError(
            f"{field} covers {covered} elements but its output axis has extent {extent}"
        )


def solver_tensor_for_value(lowered: LoweredRegion, value_id: str) -> int:
    """Return the unique lowered tensor for a normalized value."""

    matches = [
        tensor.index for tensor in lowered.tensors if tensor.value_id == value_id
    ]
    if len(matches) != 1:
        raise SourceEmissionError(
            f"value {value_id} does not map to exactly one solver tensor"
        )
    return matches[0]


def tensor_type(value: NormalizedValue) -> str:
    """Render one static rank-2 PyPTO tensor type."""

    rows, cols = static_shape(value, field=value.id)
    return f"pl.Tensor[[{rows}, {cols}], {pypto_dtype(value.dtype)}]"


def static_shape(value: NormalizedValue, *, field: str) -> tuple[int, int]:
    """Return a static rank-2 shape or fail closed."""

    if len(value.shape) != 2 or any(
        isinstance(dim, ShapeDimension) for dim in value.shape
    ):
        raise SourceEmissionError(
            f"source v1 requires a static rank-2 value, got {field}"
        )
    rows, cols = value.shape
    if not isinstance(rows, int) or not isinstance(cols, int):
        raise SourceEmissionError(f"source v1 requires static dimensions for {field}")
    return rows, cols


def pypto_dtype(dtype: str) -> str:
    """Map one normalized/lowered dtype to its PyPTO spelling."""

    names = {
        "FP32": "pl.FP32",
        "FP16": "pl.FP16",
        "BF16": "pl.BF16",
        "INT32": "pl.INT32",
        "INT16": "pl.INT16",
        "INT8": "pl.INT8",
        "BOOL": "pl.BOOL",
        "float32": "pl.FP32",
        "float16": "pl.FP16",
        "bfloat16": "pl.BF16",
        "int32": "pl.INT32",
        "int16": "pl.INT16",
        "int8": "pl.INT8",
        "bool": "pl.BOOL",
    }
    try:
        return names[dtype]
    except KeyError as error:
        raise SourceEmissionError(f"unsupported PyPTO dtype {dtype!r}") from error


def class_name(value: str) -> str:
    """Convert an arbitrary program label into a deterministic class name."""

    words = re.findall(r"[A-Za-z0-9]+", value)
    result = "".join(word[:1].upper() + word[1:] for word in words) or "FusedRegion"
    if result[0].isdigit():
        result = f"Fused{result}"
    return result


def identifier(value: str) -> str:
    """Convert an arbitrary value name into a Python identifier."""

    result = re.sub(r"\W", "_", value).strip("_") or "value"
    if result[0].isdigit() or keyword.iskeyword(result):
        result = f"value_{result}"
    return result


def unique_name(base: str, used: set[str]) -> str:
    """Reserve a deterministic unique identifier."""

    result = base
    suffix = 1
    while result in used:
        result = f"{base}_{suffix}"
        suffix += 1
    used.add(result)
    return result


def ceil_div(value: int, divisor: int) -> int:
    """Return the integer ceiling of ``value / divisor``."""

    return (value + divisor - 1) // divisor


def literal(value: Any) -> str:
    """Render a deterministic Python literal."""

    return repr(value)
