"""Public Torch/FX capture and PTO-Fusebox scheduling API."""

from .bindings import InputBindingError, bind_emitted_inputs

from .cube_sweep import (
    CUBE_PLAN_SWEEP_SCHEMA,
    CubeCandidateGrid,
    CubePlanCandidate,
    CubePlanSweep,
    enumerate_cube_plans,
    region_for_cube_candidate,
)
from .mixed_sweep import (
    MIXED_GROUP_SWEEP_SCHEMA,
    MixedCostBreakdown,
    MixedGroupCandidate,
    MixedGroupSweep,
    MixedGroupTile,
    enumerate_mixed_group_plans,
    region_for_mixed_group_candidate,
)
from .ir import (
    NORMALIZED_GRAPH_SCHEMA,
    PROBLEM_SCHEMA,
    SOLUTION_SCHEMA,
    GraphPattern,
    GraphPatternBinding,
    NormalizedGraph,
    NormalizedOp,
    NormalizedValue,
    ShapeDimension,
)
from .normalize import export_and_normalize, normalize_exported
from .model import (
    NativeBoundaryKind,
    PyPTOLibModelManifest,
    PyPTOLibNativeBoundary,
    PyPTOLibStaticRegion,
    StaticRegionOwnership,
    ValidatedPyPTOLibModel,
    pypto_lib_model_manifest,
    pypto_lib_model_manifests,
    validate_pypto_lib_model,
)
from .pypto_lib import (
    FlashMtpProjectionOverlay,
    QwenOutputHeadOverlay,
    emit_deepseek_mtp_projection_overlay,
    emit_flash_mtp_decode_projection_overlay,
    emit_qwen_output_head_overlay,
)
from .regions import SolverRegion, extract_solver_regions
from .schedule import (
    AxisPartition,
    KernelKind,
    KernelStep,
    ScheduleContractError,
    ScheduledRegion,
    scheduled_region,
)
from .solver import RegionSolveResult, SolveResult, solve_graph
from .source import (
    EmittedPyPTOCallable,
    EmittedPyPTOStaticBundle,
    EmittedPyPTOSource,
    PyPTOABIArgument,
    PyPTORuntimeValidShapeArgument,
    RuntimeValidShapeSpec,
    SourceEmissionError,
    can_emit_region,
    emit_pypto_callable,
    emit_pypto_region,
    emit_pypto_static_bundle,
)
from .target import Ascend910BTarget, TargetProfile

__all__ = [
    "NORMALIZED_GRAPH_SCHEMA",
    "PROBLEM_SCHEMA",
    "SOLUTION_SCHEMA",
    "Ascend910BTarget",
    "AxisPartition",
    "CUBE_PLAN_SWEEP_SCHEMA",
    "CubeCandidateGrid",
    "CubePlanCandidate",
    "CubePlanSweep",
    "EmittedPyPTOCallable",
    "EmittedPyPTOStaticBundle",
    "EmittedPyPTOSource",
    "FlashMtpProjectionOverlay",
    "GraphPattern",
    "GraphPatternBinding",
    "InputBindingError",
    "KernelKind",
    "KernelStep",
    "NormalizedGraph",
    "NormalizedOp",
    "NormalizedValue",
    "NativeBoundaryKind",
    "PyPTOABIArgument",
    "PyPTOLibModelManifest",
    "PyPTOLibNativeBoundary",
    "PyPTOLibStaticRegion",
    "PyPTORuntimeValidShapeArgument",
    "QwenOutputHeadOverlay",
    "RegionSolveResult",
    "RuntimeValidShapeSpec",
    "ScheduleContractError",
    "ScheduledRegion",
    "ShapeDimension",
    "SolveResult",
    "SolverRegion",
    "SourceEmissionError",
    "StaticRegionOwnership",
    "TargetProfile",
    "ValidatedPyPTOLibModel",
    "can_emit_region",
    "bind_emitted_inputs",
    "export_and_normalize",
    "emit_pypto_callable",
    "emit_deepseek_mtp_projection_overlay",
    "emit_flash_mtp_decode_projection_overlay",
    "emit_qwen_output_head_overlay",
    "emit_pypto_region",
    "emit_pypto_static_bundle",
    "enumerate_cube_plans",
    "MIXED_GROUP_SWEEP_SCHEMA",
    "MixedCostBreakdown",
    "MixedGroupCandidate",
    "MixedGroupSweep",
    "MixedGroupTile",
    "enumerate_mixed_group_plans",
    "region_for_mixed_group_candidate",
    "extract_solver_regions",
    "normalize_exported",
    "pypto_lib_model_manifest",
    "pypto_lib_model_manifests",
    "region_for_cube_candidate",
    "scheduled_region",
    "solve_graph",
    "validate_pypto_lib_model",
]
